/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/

//Logic: Maintain count of each letter in 26 size array and play around it.

public class Solution {
    public char findTheDifference(String s, String t) {
        
        int[] bigArray = new int[26];
        
        for(int i=0; i<t.length(); i++){
            bigArray[t.charAt(i)-'a']++;
        }
        
        for(int i=0; i<s.length(); i++){
            bigArray[s.charAt(i)-'a']--;
        }
        
        char a = 'a';
        for(int i=0; i<bigArray.length; i++){
            if(bigArray[i]!=0){
                a = (char) ('a' + i);
                break;
            }
        }
        return a;
    }
}